sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
addons:
  postgresql: "9.4"
env:
  - BLINKER=1 DATABASE_URI=postgresql://localhost/travis_ci_test
  - BLINKER=1 DATABASE_URI=sqlite://
  - BLINKER=0 DATABASE_URI=sqlite://
matrix:
  include:
  - name: "Black"
    python: 3.6
    install: travis_retry pip install black
    script: black --check .
    after_success: skip
  - name: "Documentation"
    python: 3.6
    addons:
      apt:
        packages:
          - python3-enchant
          - aspell-en
    install:
    - travis_retry pip install -r requirements.txt
    - travis_retry pip install -r docs/requirements.txt
    - pip install -e .
    before_script: skip
    script:
    - cd docs
    - make linkcheck
    - make spellcheck
    - make html
    after_success: skip

branches:
  only:
  - master

before_script:
  - if [[ $DATABASE_URI == postgresql* ]]; then psql -c 'create database travis_ci_test;' -U postgres; fi
install:
  - travis_retry pip install -U pytest
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r tests/requirements.txt
  - if [[ $BLINKER == 1 ]]; then travis_retry pip install blinker; fi
  - if [[ $DATABASE_URI == postgresql* ]]; then travis_retry pip install psycopg2; fi
  - travis_retry pip install codecov
  - pip install -e .
script:
  - coverage run -m pytest
after_success:
  - codecov
